apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: elastic
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: elastic
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
              value: "123"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: cluster.name
              value: docker-cluster
            - name: discovery.type
              value: single-node
            - name: http.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: "true"
          image: elasticsearch:7.17.7
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /elasticsearch-data
              name: elastic-data
      restartPolicy: Always
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: elastic-data
status: {}
